# Generated by Django 3.2.11 on 2022-02-01 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(default='', max_length=50)),
                ('roll_number', models.BigIntegerField(default='')),
                ('college', models.CharField(default='', max_length=50)),
                ('year', models.CharField(default='', max_length=10)),
                ('gender', models.CharField(default='', max_length=5)),
                ('password', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
